[project]
name = "llm-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "openai>=1.77.0",
    "tiktoken>=0.9.0",
    "uvicorn>=0.34.2",
]
